void transformMaiusculo(char string[]);
void limparTela();
void imprimir_linhas();
void limparString(char string[]);
void limparBuffer();
int tamString(char string[]);
int trueIndexPessoa(int input, ficha_pessoa pessoa[]);
int trueIndexDisciplina(int input, ficha_disciplina disciplinas[]);
int checkMatriculado(ficha_disciplina disciplinas[], ficha_pessoa alunos[], int index_disc, int index_alunos);
int mesInt (char validNasc[]);
int diaInt(char validNasc[]);
int anoInt(char validNasc[]);
void instrucoes();
int AddMatricula();